[google_auth]
client_config_backend = "web"

[google_auth.client_config]
client_id = "679703327458-abrvnhpnm111qffkak6cm1r6gkfgo6f2.apps.googleusercontent.com"
client_secret = "GOCSPX-efqVflxqVplvCoka40YzjxgDQx"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
redirect_uris = ["http://localhost"]

# Optionally, if you already have a users.json file on Drive, specify its file ID.
users_json_file_id = "https://drive.google.com/file/d/12YPmUZQ5-31UM74N-9T2U2LkR1Kzygqh/view?usp=drive_link"

[redis]
# host = "redis-16577.c330.asia-south1-1.gce.redns.redis-cloud.com:16577"
# port = 6379
# password = "RedisInsight-e35dc5d6-c268-1742427422342"  # Remove if not applicable